name: Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build-release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build.zip
          path: build/
          if-no-files-found: error
