name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build:release

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'artifacts/*'
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
