name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build:ci
